version: '3'
services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
volumes:
  data: